# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: HomeInsuranceDatabase
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-db-storage
        emptyDir: {}
---
# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-db
  type: ClusterIP
